### ISSUE TITLE
Cython backend troubles

### ISSUE THREAD

**Issue by florianscheidl** [yoongi0428/RecSys_PyTorch#2]
Hi yoongi0428,

Thanks a lot for sharing this extensive recommender system implementation.
I have tried to run your code on python 3.8, however I run into trouble with the cython backend.
I get an error of the form:

/local/home/scheidlf/.pyxbld/temp.linux-x86_64-3.8/pyrex/utils/backend/cython/tool.c:610:10: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I was wondering if you could share the environment you worked with or let us know which packages are required to run the code.

Best,
Flo

**Comment by yoongi0428** [comment]
Hi, thanks for your interest.

I missed setup.py and the script to run for c++ backend.
Now I updated with the instruction on README.
Please try and let me know if it works.

And for the environment, I'll add requirement file soon after fixing and testing the environment.
Current environment uses pytorch==1.5.1, pandas 1.1.0.

**Comment by florianscheidl** [comment]
Hi, thanks for the quick reply!
After running setup.py, the code worked. :)
